### ISSUE TITLE
Errors not properly send to zipkin

### ISSUE THREAD

**Issue by Landerstraeten** [jcchavezs/zipkin-instrumentation-symfony#40]
Errors not properly send to zipkin due to a bad request http call.
The error tag must be set to a string with value "true" not the HTTP status code.

**Comment by jcchavezs** [comment]
Ping @adriancole

Den tor. 21. mar. 2019, 10:41 skrev Lander Vanderstraeten <
notifications@github.com>:

**Comment by jcchavezs** [comment]
I am not entirely sure this is an issue. Other server frameworks uses the status code for error:

- https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java#L145
-  https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/server.go#L138

cc @adriancole

**Comment by UrGuardian4ngel** [comment]
I can confirm this is also an issue for us.

Because I have a similar issue in my project?
Normal tracing works, but requests with exceptions (`'error'` traces) get dropped, due to a `400` on our tracing collector.

Tried it via CURL as well (manually).
- with `"error": 500` in the payload, I get a `400` from our collector
- with `"error": "500"` it's a `202`.

But OpenTracing docs say, it should be `'true'`, and not the **response status code**.
There is `http.status_code` for that... 😉 

Tested #41 patch in that project, and now exceptions are _also_ traced... 👌 
So it seems to do the trick for us?

**Comment by jcchavezs** [comment]
> with `"error": "500"` it's a 202.

In zipkin tags are supposed to be string always. This PR fixes this: https://github.com/jcchavezs/zipkin-instrumentation-symfony/pull/43

**Comment by jcchavezs** [comment]
In our case when there is an exception we include the exception message and
when there is a request with status code >399 we include the code, I know
symfony has a translation table from status code into message (see
https://github.com/symfony/http-foundation/blob/master/Response.php#L131)
but I am not sure that is more useful than the status code. *As users, will
that be more useful to you, people?*


Den tor. 21. mar. 2019, 16:18 skrev Michaël Jacobs <notifications@github.com
